### ISSUE TITLE
ReadMe lists FlightOne as an FC you can purchase.

### ISSUE THREAD

**Issue by Quick-Flash** [spracing/spracingpixelosd#2]
![image](https://user-images.githubusercontent.com/46289813/221003698-f2229abb-2975-44f9-a6bd-07b98e73b1c1.png)
FlightOne no longer ships orders of FC, while still taking in orders of FC's. We should not continue promoting this behaviour, and you should add some sort of note to show that you do not recommend someone place an order with FlightOne. This may make people unknowingly think that they could purchase a FlightOne FC.

**Comment by Colossal-John** [comment]
Will this firmware work with f1 h7? Can't seem to get it to display osd on analog... Will u be the hero to help those that have been left hanging a chance to at least enjoy and use what Dominic has designed?

**Comment by hydra** [comment]
> Will this firmware work with f1 h7? Can't seem to get it to display osd on analog with betaflight... Will u be the hero to help those that have been left hanging a chance to at least enjoy and use what Dominic has designed?

Well, I made a target for the F1 H7 Lightning but it's not been updated in years, you can find it in the PR to BF for the SPRacingPixelOSD, it's codename is the SPRacingH7NP.

Yes, the SPRacingPixelOSD firmware itself, from this repo will work.

The BF target would need porting to BF 4.5, then use the SPRacing BF fork and the latest H7RF support branch.  However then you would also need a bootloader that can load the BF firmware and OSD bios on boot.  

Yes it's technically possible, and the H7 Lightning was originally developed running BF before the OSD code was moved to a bios so it could be used in both BF and F1.
